version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_demo
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"


  backend:
    build: ./backend
    container_name: go-backend
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:
